[build]
functions = "./functions"
upload = { format = "modules" }

[[routes]]
pattern = "/send-email"
methods = ["GET", "POST", "OPTIONS"]
type = "function"

[[routes]]
pattern = "/ping"
methods = ["GET", "POST", "OPTIONS"]
type = "function"

